export const porkDishes = Array.from({ length: 10 }, (_, i) => ({
  id: `pork-${i}`,
  index: i,
  image: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
  title: `Свинина блюдо ${i + 1}`,
  rating: 4 + (i % 2) * 0.5,
  isLiked: i % 2 === 0,
  like: 1000 + i * 50,
  author: `Chef Pork ${i}`,
  authorAvatar: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
  video: i % 3 === 0,
  lang: ['ru'],
  category: 'Мясо',
  subcategory: 'Свинина',
}));
export const beefDishes = Array.from({ length: 10 }, (_, i) => ({
  id: `beef-${i}`,
  index: i,
  image: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
  title: `Говядина блюдо ${i + 1}`,
  rating: 4.2 + (i % 3) * 0.3,
  isLiked: i % 2 !== 0,
  like: 1200 + i * 60,
  author: `Chef Beef ${i}`,
  authorAvatar: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
  video: i % 2 === 0,
  lang: ['ru', 'ua'],
  category: 'Мясо',
  subcategory: 'Говядина',
}));
export const lambDishes = Array.from({ length: 10 }, (_, i) => ({
  id: `lamb-${i}`,
  index: i,
  image: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
  title: `Баранина блюдо ${i + 1}`,
  rating: 4.1 + (i % 4) * 0.2,
  isLiked: i % 3 === 0,
  like: 800 + i * 40,
  author: `Chef Lamb ${i}`,
  authorAvatar: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
  video: i % 4 === 0,
  lang: ['ru'],
  category: 'Мясо',
  subcategory: 'Баранина',
}));
export const poultryDishes = [
  ...['Курица', 'Перепела', 'Индейка', 'Утка', 'Другие птицы'].flatMap(subcat =>
    Array.from({ length: 10 }, (_, i) => ({
      id: `${subcat.toLowerCase()}-${i}`,
      index: i,
      image: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      title: `${subcat} блюдо ${i + 1}`,
      rating: 4 + (i % 2) * 0.4,
      isLiked: i % 2 === 0,
      like: 900 + i * 30,
      author: `Chef ${subcat} ${i}`,
      authorAvatar: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      video: i % 3 === 1,
      lang: ['ru'],
      category: 'Птица',
      subcategory: subcat,
    })),
  ),
];
export const saladDishes = [
  ...['Мясные', 'Рыбные', 'Овощные', 'Эксклюзивные'].flatMap(subcat =>
    Array.from({ length: 10 }, (_, i) => ({
      id: `salad-${subcat}-${i}`,
      index: i,
      image: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      title: `${subcat} салат ${i + 1}`,
      rating: 4.2 + (i % 3) * 0.2,
      isLiked: i % 2 !== 0,
      like: 600 + i * 40,
      author: `Chef Salad ${subcat} ${i}`,
      authorAvatar: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      video: i % 2 === 0,
      lang: ['ua'],
      category: 'Салаты',
      subcategory: subcat,
    })),
  ),
];
export const snackDishes = [
  ...['Сандвичи', 'Рыбные закуски', 'Мясные закуски'].flatMap(subcat =>
    Array.from({ length: 10 }, (_, i) => ({
      id: `snack-${subcat}-${i}`,
      index: i,
      image: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      title: `${subcat} ${i + 1}`,
      rating: 4.0 + (i % 2) * 0.5,
      isLiked: i % 2 === 1,
      like: 700 + i * 25,
      author: `Chef Snack ${subcat} ${i}`,
      authorAvatar: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      video: i % 3 === 0,
      lang: ['ru'],
      category: 'Закуски',
      subcategory: subcat,
    })),
  ),
];
export const dessertDishes = [
  ...[
    'Торты',
    'Прероженые',
    'Мороженое',
    'Выпечка',
    'Желе',
    'Пряник',
    'Конфеты',
    'Печенье',
  ].flatMap(subcat =>
    Array.from({ length: 10 }, (_, i) => ({
      id: `dessert-${subcat}-${i}`,
      index: i,
      image: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      title: `${subcat} десерт ${i + 1}`,
      rating: 4.3 + (i % 3) * 0.1,
      isLiked: i % 2 === 0,
      like: 1500 + i * 100,
      author: `Chef Dessert ${subcat} ${i}`,
      authorAvatar: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      video: i % 2 === 1,
      lang: ['ru'],
      category: 'Десерт',
      subcategory: subcat,
    })),
  ),
];
export const drinkDishes = [
  ...['Смузи', 'Коктейль', 'Настойки'].flatMap(subcat =>
    Array.from({ length: 10 }, (_, i) => ({
      id: `drink-${subcat}-${i}`,
      index: i,
      image: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      title: `${subcat} напиток ${i + 1}`,
      rating: 4.1 + (i % 3) * 0.2,
      isLiked: i % 3 === 0,
      like: 500 + i * 20,
      author: `Chef Drink ${subcat} ${i}`,
      authorAvatar: `https://media.istockphoto.com/id/1829241109/it/foto/godersi-un-brunch-insieme.jpg?s=1024x1024&w=is&k=20&c=2B00_fh7byGrcg63_XXlpsoDTpfY9KGvEedV3AHlkLI=`,
      video: i % 2 === 0,
      lang: ['ru', 'ua'],
      category: 'Напитки',
      subcategory: subcat,
    })),
  ),
];
